# Generated by Django 3.2.8 on 2021-12-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categorystock_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorystock',
            name='order',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.IntegerField(default=10000000),
        ),
    ]
