# Generated by Django 3.2.8 on 2021-12-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211212_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=10000000),
        ),
    ]
