# Generated by Django 3.2.8 on 2021-12-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderdetail_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='identifiant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
