# Generated by Django 3.2.8 on 2021-11-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_orderdetail_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
