# Generated by Django 3.2.8 on 2021-12-15 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdjmember',
            name='indentifiant',
            field=models.CharField(default=uuid.UUID('fb2af613-18db-44f0-bbb5-704a7b3427c1'), max_length=100, null=True),
        ),
    ]
