# Generated by Django 3.2.8 on 2021-12-15 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_mdjmember_indentifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdjmember',
            name='indentifiant',
            field=models.CharField(default=uuid.UUID('f72c41f5-a19f-48e0-a356-3bbd1b611993'), max_length=100, null=True),
        ),
    ]
