# Generated by Django 3.2.8 on 2021-12-15 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_mdjmember_indentifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdjmember',
            name='parrain',
            field=models.CharField(default='NC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='indentifiant',
            field=models.CharField(default=uuid.UUID('79671c89-df43-48d4-80bf-ba34160554da'), max_length=100, null=True),
        ),
    ]
