# Generated by Django 3.2.8 on 2021-11-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdjmember',
            name='ordre',
            field=models.IntegerField(null=True),
        ),
    ]
