# Generated by Django 3.2.8 on 2021-11-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_mdjmember_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdjmember',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='birthday',
            field=models.DateField(verbose_name='Date_De_Naissance'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ville', to='base.city'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='ordre',
            field=models.IntegerField(auto_created=True, null=True, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, verbose_name='Numéro_De_Téléphone'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='photo',
            field=models.ImageField(upload_to='media/base/member', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='base.role', verbose_name='Role'),
        ),
    ]
