# Generated by Django 3.2.8 on 2021-12-31 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_mdjmember_indentifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdjmember',
            name='code_parrain',
            field=models.CharField(default='NC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='indentifiant',
            field=models.CharField(default=uuid.UUID('081cca74-ab87-4bc0-9414-33cc7cc074e3'), max_length=100, null=True),
        ),
    ]
