# Generated by Django 3.2.8 on 2021-11-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211111_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdjmember',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Date_De_Naissance'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/base/member', verbose_name='Photo'),
        ),
    ]
