# Generated by Django 3.2.8 on 2021-11-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211113_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdjmember',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='base.role', verbose_name='Role'),
        ),
    ]
