# Generated by Django 3.2.8 on 2021-11-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_mdjmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdjmember',
            name='ordre',
            field=models.IntegerField(auto_created=True, default=0, verbose_name='Ordre'),
        ),
    ]
