# Generated by Django 3.2.8 on 2021-11-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_mdjmember_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='nombre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
