# Generated by Django 3.2.8 on 2021-12-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_study_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdjmember',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
