# Generated by Django 3.2.8 on 2021-12-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_mdjmember_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdjmember',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='mdjmember',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Nom'),
        ),
    ]
